version: "3.8"

services:
  fastapi:
    build: .                # build từ Dockerfile ở thư mục hiện tại
    ports:
      - "8000:8000"
    volumes:
      - .:/app              # mount mã nguồn để dùng --reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
